theme: minima
minima:
  skin: dark
  social:
    - icon: github
      url: https://github.com/yuidvg
author:
  name: Yui Nishimura
  email: tremors_beau.9z [at] icloud.com
  url: https://github.com/yuidvg
